[general]
name = "RayTracing-Fix"

version = "0.1.0"

fix_version = "*"

[build]
files = ["main.fix"]
ld_flags = ["-lm"]

[[dependencies]]
name = "random"
version = "1.1.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }